"""Made the necessary relationships.

Revision ID: 18b0068c3898
Revises: 3c17f363a88a
Create Date: 2022-05-26 22:11:53.388965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b0068c3898'
down_revision = '3c17f363a88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'shows', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'start_time')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###
