"""Updated the Boolean functions in the Models.

Revision ID: 24485323c4fc
Revises: 728bb924fbba
Create Date: 2022-05-27 00:06:04.784035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24485323c4fc'
down_revision = '728bb924fbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('venues', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('artists', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
