"""Just added the venues relationship.

Revision ID: 728bb924fbba
Revises: 18b0068c3898
Create Date: 2022-05-26 23:20:32.820009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728bb924fbba'
down_revision = '18b0068c3898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
