"""Added the date_created column to help sort the Artists and Venues by the date created

Revision ID: ae3924a1d0f3
Revises: 24485323c4fc
Create Date: 2022-06-01 11:33:31.807023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3924a1d0f3'
down_revision = '24485323c4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'date_created')
    op.drop_column('artists', 'date_created')
    # ### end Alembic commands ###
